server:
  port: 8010

# 数据库的连接新
spring:
  application:
    name: mall-coupon
  datasource:
    username: root
    password: root
    url: jdbc:mysql://120.26.4.95:3306/msbmall_sms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 120.26.4.95:8848

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto # 主键自增
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

